"""add_image_url_to_projects

Revision ID: 90de70892894
Revises: add_new_roles_001
Create Date: 2026-01-27 16:39:07.407411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90de70892894'
down_revision: Union[str, None] = 'add_new_roles_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.drop_column('projects', 'internal_prompt')
    op.drop_column('projects', 'main_features')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('main_features', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('internal_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'image_url')
    # ### end Alembic commands ###
